### ISSUE TITLE
windows 编译下的错误

### ISSUE THREAD

**Issue by mkapai** [keengo99/kasync#2]
使用  
cmake 
vs 2022
windows 11 x64 debug 环境编译
inclde\kasync_file.h 文件
在下面 union  里面未定义任何成员 会导致编译失败
`
struct kasync_file_s {
	union {
#ifdef LINUX_EPOLL
		struct iocb iocb;
#endif
#ifdef BSD_OS
		struct aiocb iocb;
#endif
#ifdef KF_ASYNC_WORKER
		kf_aiocb kiocb;
#endif
	};
#ifdef KF_ASYNC_WORKER
	int offset_adjust;
	int length;
	FILE_HANDLE fd;
	int flags;
	KOPAQUE data;
	kselector *selector;
#else
	kselectable st;
#endif
	char *buf; //deprecated
	void *arg;
	aio_callback cb;
};
`

**Comment by keengo99** [comment]
fixed
